<div id="wrapper">
 <div id="operataion">
  	<h1>Operations</h1>

<a id="addTech" href="<?php echo $this->url(array(
                       'controller' =>  'manage', 
                       'action'  => 'employees')); ?>">
                       Employees</a>

<a id="techServices" href="<?php echo $this->url(array(
                       'controller' =>  'manage', 
                       'action'  => 'services')); ?>">
                       Shop Services</a>

<a id="shopHourz" href="<?php echo $this->url(array(
                       'controller' =>  'manage', 
                       'action'  => 'shop-hours')); ?>">
                       Shop Hours</a>
					   
					   
					   
					     </div>

<div id ="contentarea"> 
<h1>Add Service</h1>
<?php echo $this->form; ?>

	<?php 
		if(isset($this->successMsg))
		{
			echo $this->successMsg;
		}
	?>

 <a id="serviceslogin" class="serviceslogin " href="<?php echo $this->url(array(
                       'controller' =>  'manage', 
                       'action'  => 'services')); ?>">
                       Back</a>
</div>
</div>