<div id="wrapper">
   <div id="operataion">
  	<h1>Operations</h1>

<a id="addTech" href="<?php echo $this->url(array(
                       'controller' =>  'manage', 
                       'action'  => 'employees')); ?>">
                       Employees</a>

<a id="techServices" href="<?php echo $this->url(array(
                       'controller' =>  'manage', 
                       'action'  => 'services')); ?>">
                       Shop Services</a>

<a id="shopHourz" href="<?php echo $this->url(array(
                       'controller' =>  'manage', 
                       'action'  => 'shop-hours')); ?>">
                       Shop Hours</a>

					                        
<a id="couponsFooter" href="/manage/coupons">Coupons</a>

<a href="<?php  echo BASE_URL; ?>appointments/recentappointments">Reports</a> 
     
					     </div>
<div id ="coupons"> 
<?php
echo $this->form;
?>
</div>
</div>