<div id="wrapper">
<div id ="contentarea" style="min-height:300px;">



<div style=" margin-left: 400px;">
<h1 a> Gift Cards </h1>
<?php

echo $this->form;

?>


</div>

<!--
<form method='post' action="https://secure.authorize.net/gateway/transact.dll">
<input type='hidden' name="x_login" value="<?php echo $api_login_id?>" />
<input type='hidden' name="x_fp_hash" value="<?php echo $fingerprint?>" />
<p> Amount of Gift Card Balance($) </p>
<input type='text' name="x_amount" value="<?php echo $amount?>" />


<p> First Name </p>
<input type='text' name="x_first_name" value="" />



<p> LastName </p>
<input type='text' name="x_last_name" value="" />


<p> Email </p>
<input type='text' name="x_email" value="" />

<br />
<p>Address</p>

<input type='text' name="x_address" value="" />



<p>City</p>

<input type='text' name="x_city" value="" />



<p>State</p>

<input type='text' name="x_state" value="" />



<p>Zip</p>

<input type='text' name="x_zip" value="" />

<p>Description/Note</p>

<textarea rows="8" cols="40" name="x_description"></textarea>

<br/>



 
<br />

<input type='hidden' name="x_fp_timestamp" value="<?php echo $fp_timestamp?>" />
<input type='hidden' name="x_fp_sequence" value="<?php echo $fp_sequence?>" />
<input type='hidden' name="x_version" value="3.1">
<input type='hidden' name="x_show_form" value="payment_form">
<input type='hidden' name="x_test_request" value="false" />
<input type='hidden' name="x_method" value="cc">

<input type='hidden' name="x_method" value="true">

<INPUT TYPE=HIDDEN NAME="x_relay_response" VALUE="TRUE"> 
<INPUT TYPE=HIDDEN NAME="x_relay_url" VALUE="http://admin.nailsrock.biz/giftcardext/confirm-giftcard">


<INPUT TYPE=HIDDEN NAME="x_receipt_link_method" VALUE="POST">
<INPUT TYPE=HIDDEN NAME="x_receipt_link_text" VALUE="Click here to return 
to Nailsrock home page">
<INPUT TYPE=HIDDEN NAME="x_receipt_link_URL" VALUE="http://admin.nailsrock.biz/giftcard/confirm-giftcard">

<input type='submit' value="Click here for the secure payment form">
</form>
-->
  
</div>
</div>




