

<form id="changeappointmentform" action="<?php  echo $this->baseUrl(); ?>/appointments/save-appointment" method="post" enctype="application/x-www-form-urlencoded">


<style type="text/css">
<!--
	#appointments{
	   height: 1200px;
	}
-->
</style>
<?php
	  $AllTechnicalHoursfordate=$this->AllTechnicalHoursfordate;
?>
<div id="wrapper">
<div id ="appointments">
 <form onsubmit="return false;" method="post" 
     action="<?php  echo $this->baseUrl(); ?>/appointments/makeappointment" id="appointment-form" >
     
<div class="wideBox">
<div id="content">




<div id="cardPile">

<?php 
 $oldappointment=$this->oldappointment;
 $from=$oldappointment->reserved_hours->interval_time;
 
   $time=strtotime($from);
   
    $minutes=$oldappointment->duration;
    
    $width=$minutes;
    $widthpx=$width."px";
    
    $to=  date("h:i A", strtotime("+$minutes minutes", $time));;
        
     $firstName=$oldappointment->firstName;
     
     $serviceName=$oldappointment->serviceName;
         
      $technicianName=$oldappointment->interval_time;
        $technicianName=$oldappointment->reserved_hours->Name;
     
     $title=$firstName." for ".$serviceName." with ".$technicianName." from ".strtoupper($from)." to ".strtoupper($to) ; 

    ?>
<style type="text/css">
<!--
	table td {
	   padding: 10px;
	}
-->
</style>

<div style="height: 20px; width: 80px;" id="oldappointment" class="ui-draggable" style="position: relative;" title="<?php  echo $title; ?>">
 
<input type="hidden" name="" value="<?php  echo  $minutes; ?>" id="" class="old_duration" />

<?php   echo $firstName ; ?>
</div>
<table style="float: left;" >
<tr>
	
	<td><?php
	echo $this->form->serviceID->render();
?></td>
	<td>
<?php
	echo $this->form->date->render();
?></td>
</tr>
</table>

<input type="hidden" name="appointment_id" value="<?php  echo  $oldappointment->id; ?>" id="appointment_id" class="" />
<input type="hidden" name="time_id" value="" id="new_time_id" class="" />
<input type="hidden" name="technicianID" value="" id="new_technicianID" class="" />
</div>


<div class="technician-names">

			<?php foreach($this->Technician as $data):?>
                
					<div class="technician-name" >
						<?php echo $data["Name"]; ?>
					</div>		
					<?php
                    
                    
                       endforeach;
				?>

</div>

<div id="cardSlots">

<span id="times">

<ul>

  <?php  
         
  
           $rows=  $AllTechnicalHoursfordate;
         if (is_array($rows)) {
            
	       foreach ($rows as $row) {
	            ?>  <li>   <?php  echo $row->interval_time; ?></li>  <?php
           }
         }
    ?>

</ul>


</span>
<span id="times-slots">

  <?php  
         

  
           $rows=  $this->TechniciansAvailable;
         if (is_array($rows)) {
            
	       foreach ($rows as $technicinaID=>$timedatas) {
	            ?>    <ul> <?php
               foreach ( $timedatas as $interval_time=>$timedata   ) {
                
                
         
                if ($timedata['status']=='booked'){
                    
                    
                $duration=(int) $timedata['appointment']['duration'];
                $no_of_slots=$duration/15;
            
            
            if ($no_of_slots>1) {
                
              $offsetarray=array(2=>2,3=>4,4=>5,5=>6,6=>7,7=>8);
              $offset=$offsetarray[$no_of_slots];
                $height=$timedata['appointment']['duration']+($no_of_slots*5)+$offset;
                      $heightpx=$height."px";
                 
            }
                      
                  
        
                } else {
                     $heightpx="20px";
                }
           
  ?>  <li> 
              
              
  <div title="<?php  echo $technicinaID."_".$timedata['time_id'] ; ?>" style="height: <?php  echo $heightpx; unset($heightpx) ?>; width: 80px;" 
  class="<?php  echo $timedata['status'];?>"><?php   
  
    if ($timedata['status']=='available'){
        
         ?>     <input type="hidden" name="" value="1" id="" class="<?php  echo $technicinaID."_".$timedata['time_id'] ; ?>" />   <?php
    }
  

  
  $timedata['status'];
  
  
   ?>
  
  <input type="hidden" name="" value="<?php  echo $technicinaID."_".$timedata['time_id'] ; ?>" 
  id="" class="technician_class" />
  
  
  
   </div>  </li>  <?php  
                
	
            }
               
            
                 ?>  </ul>   <?php
           }
         }
    ?>

</span>
</div>


<div style="display: none; left: 580px; top: 250px; width: 0px; height: 0px;" id="successMessage"><h2>You did it!</h2><button onclick="init()">Play Again</button></div></div>

</form>

</div>
</div>
  

     <script type="text/javascript">
  
jQuery( '#date' ).datepicker({dateFormat:'yy-m-d'});

    $('#oldappointment').
    draggable( {
      containment: '#content',
      stack: '#cardPile div',
      cursor: 'move',
      revert: true
    } );

    $('.available').droppable( {
      accept: '#cardPile div',
      hoverClass: 'hovered',
      drop: handleCardDrop
    } );
  


function handleCardDrop( event, ui ) {



var draggable=ui.draggable;

var technician_timeId= jQuery(this).attr('title');
 var technicain_timidarr=technician_timeId.split('_');
 
 var technician=technicain_timidarr[0];
 

 var time_id=technicain_timidarr[1];
 var no_slots=jQuery(draggable).find('.old_duration').val()/15;
 

var required_slots=0;

 for (var i=0;i<no_slots;i++) {
	
    var new_time_id=parseInt(time_id)+i;
    
    var selector="."+technician+"_"+new_time_id;
    
    //   alert(selector);
    if (jQuery(selector ).val() ){
        
        required_slots++;
    }
}

if (required_slots==no_slots){
   
   var confirm_flag=confirm('Reschedule is possible. Are you sure?');
   
   if ( confirm_flag ){
    // now send request to server to change the appointment ( service, technician, time slot, date  )
     
     jQuery( '#new_time_id' ).val(time_id);
    jQuery( '#new_technicianID' ).val(technician);
    jQuery('#changeappointmentform').submit();
   }
    
    
} else {
    
    alert("Reschedule is not possible");
}
 
jQuery('#dump').html(jQuery(this).attr('title'));

var flag=false;

  if ( flag ) {
    ui.draggable.addClass( 'correct' );
    ui.draggable.draggable( 'disable' );
    $(this).droppable( 'disable' );
    ui.draggable.position( { of: $(this), my: 'left top', at: 'left top' } );
    ui.draggable.draggable( 'option', 'revert', false );
    correctCards++;
  } 
  


}

</script>



</form>