  <script type="text/javascript">
  $(function(){

    $("button, input[type='button']").click(function(){

     // alert("hello clicked");
      return false;
      
    });
  });
</script>
<style type="text/css">
.dijitReset  {

   padding: 2px;
}
.odd {
   background: #ccc;
}

</style>
<div id="wrapper">

  <div id="contentarea">
  	<h1>Recent Members</h1>
    
    
<div id="accountsmember_table" style="float: left;">

     <table class="sortable">
     <thead class="titlestrip">
        <th> <div style="color: white; text-align: center; width: 50px; font-weight: bold;" >No.</div> </th>
        <th> <div style="color: white; width: 250px; font-weight: bold;">Member Name</div>   </th>
      
        <th > <div style="color: white;font-weight: bold;">Date</div> </th>
          <th>  <div style="color: white;width: 400px; font-weight: bold;">Note</div> </th>
     </thead>
     
<tbody>

    <?php
        $i=0;
     foreach($this->allAppointments as $t):
    

     ?>
    
<tr>
	<td style="text-align: center;"><?php  echo $i; ?></td>
	<td> <a href="<?php echo $this->Url(
                            array(
                            'controller' =>  'member',
                            'action'     =>  'view-account',
                            'memberID'         =>   1,
                            )); ?>">
                            
                            
                            
                           </a>   </td>
	<td style="width: 50px;">   </td>

	<td style="text-align: center;">

    
    </td>

   
  <?php
 

 
 ?>   </tr>  <?php
 
 $i++;
  endforeach; ?>



</tbody>
     
     
     
     </table>
</div>

     
  	<div >

		
	
		

        
		<div class="clear"></div>
	</div>
	
	<div id="editprofile">
	<div class="accountbg"> 



  </div>
 
  </div>
  <?php  // echo $this->paginationControl($this->allAppointments, 'Sliding', 'pagination.phtml');
   ?>
  </div>
  </div>
